version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build started on `date`
      # - cd backend
  build:
    commands:
      - echo Build started on `date`
      - python --version
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p ~/.ssh
      - aws s3 cp s3://bassy-terraform-state-bucket99/Nexuskeypair.pem ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ls
      - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@44.220.90.18 "mkdir -p app"
      - echo Copying files to server...
      - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r backend/* ubuntu@44.220.90.18:app
      - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@44.220.90.18 "sudo apt-get update -y && sudo apt-get install -y python3-venv && python3 -m venv app/venv && source app/venv/bin/activate && pip install --upgrade pip && pip install -r app/requirements.txt && pm2 start app/src/server.py --name todo-api --interpreter ./app/venv/bin/python3 || pm2 restart todo-api && pm2 save"
